# - name: "Install Drivers"
#   hosts: "{{ hosts_list|default('home_lemonade') }}"
#   gather_facts: true
#   vars:
#     - PATH_TASKS: "../../../tasks"
#   tasks:
#     - ansible.builtin.include_tasks:
#         file: "{{ PATH_TASKS }}/drivers/nvidia-rtx-3600.yml"

# - name: "Configure System"
#   hosts: "{{ hosts_list|default('home_lemonade') }}"
#   gather_facts: true
#   vars:
#     - PATH_TASKS: "../../../tasks"
#   tasks:

# - name: "Install System Tools..."
#   hosts: "{{ hosts_list|default('home_lemonade') }}"
#   gather_facts: no
#   vars:
#     - PATH_TASKS: "../../../tasks"
#   tasks:
