- name: "docker"
  set_fact:
    state: present

# Install
- when: ('present' in state)
  block:
    - name: "prepare"
      become: yes
      vars:
        subtask: true
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        force_apt_get: true
        state: present
    # Add docker’s official GPG key
    - name: ""
      become: yes
      vars:
        subtask: true
      ansible.builtin.command:
        cmd: |
          sudo install -m 0755 -d /etc/apt/keyrings
          wget -O https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
    - name: ""
      become: yes
      vars:
        subtask: true
      ansible.builtin.command:
        cmd: |
          echo \
          "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: "install"
      become: yes
      vars:
        subtask: true
      ansible.builtin.apt:
        name:
          - containerd.io
          - docker-buildx-plugin
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
        force_apt_get: true
        state: present
    - debug:
        msg: "{{ docker --version }}"

    - name: "configuration"
      vars:
        subtask: true
      ansible.builtin.group:
        name: docker
        state: present
    - ansible.builtin.user:
        name: '{{ user }}'
        groups: docker
        append: yes

# Uninstall
- when: ('absent' in state)
  block:
    - name: "uninstall"
      become: yes
      vars:
        subtask: true
      ansible.builtin.apt:
        name:
          - containerd.io
          - docker-buildx-plugin
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
        force_apt_get: true
        state: absent
