- name: "evince"
  debug: { msg: "" }

# Debian
# ------
- when: |
    ansible_facts["os_family"] == "Debian"
  block:
  - name: "install"
    become: yes
    vars:
      subtask: true
      nameskip: true
    ansible.builtin.apt:
      name: evince
      force_apt_get: true
      state: present
    